python scripts/train.py \
  --do_train \
  --do_predict \
  --strategy SCL \
  --type NL \
  --model MLP \
  --dataset plcifar10 \
  --lr 1e-4 \
  --batch_size 256 \
  --valid_type Accuracy \
  --output_dir output